name: Test workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        required: true
        default: 'Value1'
      input2:
        type: string
        required: true
        default: 'Value2'

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run: |
        echo ${{ inputs.input1 }}
        echo ${{ inputs.input2 }}
